FHE-DKSAP Project Proposal
eth-protocol-fellows/cohort-four pull request #208
Opened 2023-08-14 15:28 UTC by Mason-Mind

draft the proposal for FHE-DKSAP project

2023-08-14 16:11 UTC, JoshDavisLight requested changes

2023-08-14 16:11 UTC, JoshDavisLight commented on projects/FHE-DKSAP.md
> +- Meanwhile, it can prevent quantum computing attacks as well.
I would love to see more here about what your personal success metrics look like, both for EPF and generally, and less about the actual benefit that FHE-DKSAP will have on the protocol, which you outline in the Motivation section. In what stage does this project need to be for you to consider it to be successful within EPF?

2023-08-14 16:11 UTC, JoshDavisLight commented on projects/FHE-DKSAP.md
> +
Make sure to add your own name/link here, as well as anyone else you may be working with.

2023-08-14 22:17 UTC, taxmeifyoucan reviewed
Such a great proposal, I am very excited to see this!! 

One thing you could clarify in the specs/challenges part - how should wallets manage new kind of key pairs. Since you are introducing FHE-DKSAP with Paillier apart of regular secp256k1, Eth wallet would need to implement it and securely store another pair of keys. Maybe it's too much ahead, I am just wondering if there is anything you can discuss further on handling FHE keys

2023-08-21 11:04 UTC, Mason-Mind commented
@taxmeifyoucan very inspiring comment. I have added some initial thought in the implementation part. But it will need more exploring during the implementation.

2023-08-21 18:02 UTC, merged